services:
  backend:
    build: ./backend
    container_name: emotion_backend
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
    restart: always

  frontend:
    build: ./frontend
    container_name: emotion_frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: always